# Generated by Django 4.2 on 2025-09-12 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the nutritional element', max_length=100, unique=True, verbose_name='Name')),
                ('unit', models.CharField(help_text='Unit of measurement (e.g. g, mg, kcal)', max_length=50, verbose_name='Unit')),
            ],
            options={
                'verbose_name': 'Nutritional Information',
                'verbose_name_plural': 'Nutritional Information',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code of the product (Max 100)', max_length=100, unique=True, verbose_name='Code')),
                ('name', models.CharField(help_text='Name of the product', max_length=200, unique=True, verbose_name='Name')),
                ('description', models.TextField(help_text='Detailed description of the product', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the product is active', verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductNutritionalValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, help_text='Nutritional value per 100g/ml', max_digits=10, verbose_name='Value')),
                ('nutritional_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.nutritionalinformation', verbose_name='Nutritional Information')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutritional_values', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Nutritional Value',
                'verbose_name_plural': 'Product Nutritional Values',
                'unique_together': {('product', 'nutritional_info')},
            },
        ),
    ]
